// <auto-generated />
using Lab2Linq.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab2Linq.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20220422132243_AddedManyToMany")]
    partial class AddedManyToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClassCourse", b =>
                {
                    b.Property<int>("ClassesId")
                        .HasColumnType("int");

                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.HasKey("ClassesId", "CoursesId");

                    b.HasIndex("CoursesId");

                    b.ToTable("ClassCourse");

                    b.HasData(
                        new
                        {
                            ClassesId = 1,
                            CoursesId = 3
                        },
                        new
                        {
                            ClassesId = 2,
                            CoursesId = 3
                        },
                        new
                        {
                            ClassesId = 1,
                            CoursesId = 1
                        },
                        new
                        {
                            ClassesId = 2,
                            CoursesId = 2
                        });
                });

            modelBuilder.Entity("Lab2Linq.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SA13B"
                        },
                        new
                        {
                            Id = 2,
                            Name = "EK12A"
                        });
                });

            modelBuilder.Entity("Lab2Linq.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Engelska 7",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "Matematik 3B",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 3,
                            Name = "Samhällskunskap 1A",
                            TeacherId = 1
                        });
                });

            modelBuilder.Entity("Lab2Linq.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            Name = "Johanna Simonsson"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            Name = "Darya Asaad"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 2,
                            Name = "Philippos Halkias"
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 2,
                            Name = "Gina Digorno"
                        });
                });

            modelBuilder.Entity("Lab2Linq.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mr. Larsson"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mrs. Eriksson"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ms. Filipsson"
                        });
                });

            modelBuilder.Entity("ClassCourse", b =>
                {
                    b.HasOne("Lab2Linq.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab2Linq.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lab2Linq.Models.Course", b =>
                {
                    b.HasOne("Lab2Linq.Models.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Lab2Linq.Models.Student", b =>
                {
                    b.HasOne("Lab2Linq.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Lab2Linq.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Lab2Linq.Models.Teacher", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
